import 'package:flutter/material.dart';
import 'package:rent_house/data/model/housemodel/house_list_model.dart';
import 'package:rent_house/pages/user/house/houselist/house_search.dart';

class TestPage extends StatefulWidget {
  const TestPage({super.key});

  @override
  State<TestPage> createState() => _TestPageState();
}

class _TestPageState extends State<TestPage> {
  @override
  Widget build(BuildContext context) {
    List<HouseModel> houseListModel = const [
      HouseModel(
        address: 'savar',
        advanceFee: 5,
        canBook: 'dfd',
        category: 'dfdr',
        electricityFee: 547,
        fee: 101,
        gasFee: 56,
        houseId: 1,
        id: 101,
        image1: 'dfdr',
        image2: 'dfdr',
        image3: 'dfdr',
        image4: 'dfdr',
        notice: 'dfdr',
        othersFee: 452,
        ownerId: 1,
        ownerName: 'dfdr',
        ownerNumber: 'dfdr',
        quantity: 'dfdr',
        status: 'dfdr',
        time: 'dfdr',
        video: 'dfdr',
      ),
      HouseModel(
        address: 'savar',
        advanceFee: 45,
        canBook: 'dfd',
        category: 'dfdr',
        electricityFee: 45,
        fee: 100,
        gasFee: 54,
        houseId: 1,
        id: 100,
        image1: 'dfdr',
        image2: 'dfdr',
        image3: 'dfdr',
        image4: 'dfdr',
        notice: 'dfdr',
        othersFee: 54,
        ownerId: 1,
        ownerName: 'dfdr',
        ownerNumber: 'dfdr',
        quantity: 'dfdr',
        status: 'dfdr',
        time: 'dfdr',
        video: 'dfdr',
      ),
      HouseModel(
        address: 'savar',
        advanceFee: 54,
        canBook: 'dfd',
        category: 'dfdr',
        electricityFee: 45,
        fee: 102,
        gasFee: 45,
        houseId: 1,
        id: 102,
        image1: 'dfdr',
        image2: 'dfdr',
        image3: 'dfdr',
        image4: 'dfdr',
        notice: 'dfdr',
        othersFee: 45,
        ownerId: 1,
        ownerName: 'dfdr',
        ownerNumber: 'dfdr',
        quantity: 'dfdr',
        status: 'dfdr',
        time: 'dfdr',
        video: 'dfdr',
      ),
      HouseModel(
        address: 'savar',
        advanceFee: 54,
        canBook: 'dfd',
        category: 'dfdr',
        electricityFee: 54,
        fee: 2010,
        gasFee: 54,
        houseId: 1,
        id: 2010,
        image1: 'dfdr',
        image2: 'dfdr',
        image3: 'dfdr',
        image4: 'dfdr',
        notice: 'dfdr',
        othersFee: 45,
        ownerId: 1,
        ownerName: 'dfdr',
        ownerNumber: 'dfdr',
        quantity: 'dfdr',
        status: 'dfdr',
        time: 'dfdr',
        video: 'dfdr',
      ),
      HouseModel(
        address: 'savar',
        advanceFee: 45,
        canBook: 'dfd',
        category: 'dfdr',
        electricityFee: 47,
        fee: 200,
        gasFee: 7,
        houseId: 1,
        id: 200,
        image1: 'dfdr',
        image2: 'dfdr',
        image3: 'dfdr',
        image4: 'dfdr',
        notice: 'dfdr',
        othersFee: 78,
        ownerId: 1,
        ownerName: 'dfdr',
        ownerNumber: 'dfdr',
        quantity: 'dfdr',
        status: 'dfdr',
        time: 'dfdr',
        video: 'dfdr',
      ),
      HouseModel(
        address: 'asulia',
        advanceFee: 45,
        canBook: 'dfd',
        category: 'dfdr',
        electricityFee: 4,
        fee: 300,
        gasFee: 54,
        houseId: 1,
        id: 300,
        image1: 'dfdr',
        image2: 'dfdr',
        image3: 'dfdr',
        image4: 'dfdr',
        notice: 'dfdr',
        othersFee: 45,
        ownerId: 1,
        ownerName: 'dfdr',
        ownerNumber: 'dfdr',
        quantity: 'dfdr',
        status: 'dfdr',
        time: 'dfdr',
        video: 'dfdr',
      )
    ];
    return Scaffold(
      backgroundColor: Colors.cyan[200],
      appBar: AppBar(
        actions: [
          IconButton(
              onPressed: () {
                showSearch(
                  context: context,
                  delegate: HouseSearch(houseListModel: houseListModel),
                );
              },
              icon: const Icon(Icons.search)),
        ],
      ),
      body: Center(),
    );
  }
}
