name: rent_house
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  #state management
  get: ^4.6.5
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  #font
  google_fonts: ^4.0.3
  #indicator
  dots_indicator: ^2.1.0
  liquid_pull_to_refresh: ^3.0.1
  #animation
  lottie: ^2.2.0
  liquid_swipe: ^3.1.0
  rive: ^0.10.4
  #storage
  get_storage: ^2.0.3
  #bottom nav
  salomon_bottom_bar: ^3.3.1
  #date formate
  intl: ^0.18.0
  #button
  chips_choice_null_safety: ^2.0.6
  custom_radio_grouped_button: ^2.1.2+2
  #alert dialog
  cool_alert: any
  loading_overlay: ^0.3.0
  #slider
  velocity_x: any
  carousel_slider: ^4.2.1
  #payment
  flutter_sslcommerz: ^2.2.2-nullsafety.0
  #screen size
  flutter_screenutil: ^5.6.1
  device_preview: any
  #grid view
  flutter_staggered_grid_view: ^0.6.2
  #network
  dio: ^5.1.1
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  #location
  geolocator: ^9.0.2
  geocoding:
  geocode:
  geocoder: any 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/animations/
    - asset/icons/
    - asset/images/
    - asset/logo/

  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
